### ISSUE TITLE
other hidden traffic

### ISSUE THREAD

**Issue by Waltervizzi** [arvinjarvin/SimAware#2]
Hi, I was asking about the possibility of having the other traffic visible when you have your flight selected like a flyer, it's very unpleasant that when you click on your flight all the others disappear

**Comment by arvinjarvin** [comment]
Hi

Can you elaborate a little more?

I don't understand

**Comment by Waltervizzi** [comment]
when you click on a plane all the others disappear and it's an unpleasant thing it would be nice if when you click on a plane it highlights yours but the other planes also remain visible

**Comment by arvinjarvin** [comment]
Could you show me a picture?

**Comment by Waltervizzi** [comment]
yes when not selected airplane 
![Screenshot 2023-12-26 125452](https://github.com/arvinjarvin/SimAware/assets/127858800/750a4e6c-3704-471d-994f-dcaf685880a7)
 and when select airplane the another traffic they disappear
![Screenshot 2023-12-26 12565021122](https://github.com/arvinjarvin/SimAware/assets/127858800/2754c9e4-88f6-4e42-94dc-373d7df59778)

**Comment by arvinjarvin** [comment]
Sorry. You are using VATSIM SimAware. I do not create or manage this.

My SimAware is a different application for Discord.

Please contact VATSIM.
